### ISSUE TITLE
Hang when attempting to index NodaTime

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-dotnet#48]
Repro steps:

```
git clone https://github.com/nodatime/nodatime
cd nodatime && git checkout c6158de491e041c07a8a12147676e57683302554
docker run -v $(pwd):/app sourcegraph/scip-dotnet:latest scip-dotnet index src/NodaTime.sln
```

scip-dotnet image hash: a4b074f00f73

Output:

```
❯ docker run -v $(pwd):/app sourcegraph/scip-dotnet:latest scip-dotnet index src/NodaTime.sln
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
04:28:15 info: ScipDotnet.IndexCommandOptions[0] $ dotnet restore /app/src/NodaTime.sln /p:EnableWindowsTargeting=true
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'restore' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible .NET SDK was not found.

Requested SDK version: 6.0.200
global.json file: /app/global.json

Installed SDKs:

Install the [6.0.200] .NET SDK or update [/app/global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
7.0.305 [/usr/share/dotnet/sdk]
A compatible .NET SDK was not found.

Requested SDK version: 6.0.200
global.json file: /app/global.json

Installed SDKs:

Install the [6.0.200] .NET SDK or update [/app/global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
```

After this, it seems like it just gets stuck.

**Comment by varungandhi-src** [comment]
When using scip-dotnet installed globally on Linux (the previous approach was using Docker on macOS), I got a more useful stack trace.

I'm guessing this is related to this .NET version bit in the README

> Note that scip-dotnet is built against .NET 7.0 and won't run with older versions

nodatime is a pretty popular library, so it'd be nice if we could index it out-of-the-box.

```
Unhandled exception: System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at ScipDotnet.Program.CreateWorkspace() in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/Program.cs:line 74
   at ScipDotnet.Program.<>c.<Main>b__0_11(IServiceProvider _) in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/Program.cs:line 62
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at ScipDotnet.ScipIndexer.IndexProject(IHost host, IndexCommandOptions options, FileInfo rootProject, HashSet`1 indexedProjects)+MoveNext() in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/ScipIndexer.cs:line 55
   at ScipDotnet.ScipIndexer.IndexProject(IHost host, IndexCommandOptions options, FileInfo rootProject, HashSet`1 indexedProjects)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at ScipDotnet.ScipIndexer.IndexDocuments(IHost host, IndexCommandOptions options)+MoveNext() in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/ScipIndexer.cs:line 44
   at ScipDotnet.ScipIndexer.IndexDocuments(IHost host, IndexCommandOptions options)+MoveNext() in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/ScipIndexer.cs:line 44
   at ScipDotnet.ScipIndexer.IndexDocuments(IHost host, IndexCommandOptions options)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at ScipDotnet.IndexCommandHandler.ScipIndex(IHost host, IndexCommandOptions options) in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/IndexCommandHandler.cs:line 64
   at ScipDotnet.IndexCommandHandler.ScipIndex(IHost host, IndexCommandOptions options) in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/IndexCommandHandler.cs:line 64
   at ScipDotnet.IndexCommandHandler.Process(IHost host, List`1 projects, String output, FileInfo workingDirectory, List`1 include, List`1 exclude, Boolean allowGlobalSymbolDefinitions) in /home/runner/work/scip-dotnet/scip-dotnet/ScipDotnet/IndexCommandHandler.cs:line 38
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
